### ISSUE TITLE
V/v xin dữ liệu

### ISSUE THREAD

**Issue by caodoanh2001** [Flavius1996/VNTS-faster-rcnn#1]
Em chào a,

Dạ e được biết khóa luận anh làm về đề tài phát hiện và phân loại biển báo giao thông ạ, anh cho phép em xin dữ liệu **VNTSDB** để làm đồ án môn học được không ạ?

em cảm ơn a.

**Comment by Tin-Hoang** [comment]
Dataset VNTSDB anh đã để public cho mọi người đều có thể download:
https://drive.google.com/drive/folders/0B9hMAZTpHpyCclFwT2NFWTRYSjg?usp=sharing

Em cứ thoải mái dùng cho đồ án và research nhé.

**Comment by caodoanh2001** [comment]
Em cảm ơn anh nhiều lắm,
Chúc anh thành công trong công việc ạ.
